config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update]
  root to: "homes#index"
  resources :homes do
    member do
      patch :purchase
    end
  end
  resources :memos, except: [:show]
  get 'memos/:id', to: 'memos#checked'
  resources :commodities
  resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commodity.rb
class Commodity < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :content
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
  has_many :memos
  has_many :commodities
  has_many :foods

  validates :group_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:group_name])
  end
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  before_action :set_commodity, only: [:show, :edit, :update, :destroy]
  before_action :move_to_registration

  def index
    @commodities = Commodity.all.order(id: "DESC")
  end

  def new
    @commodity = Commodity.new
  end

  def create
    @commodity = Commodity.new(commodity_params)
    if @commodity.save
      redirect_to "/commodities"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @commodity.update(commodity_params)
      redirect_to commodity_path(@commodity.id)
    else
      render :edit
    end
  end

  def destroy
    @commodity.destroy
    redirect_to "/commodities"
  end

  private

  def commodity_params
    params.require(:commodity).permit(:image, :name, :price, :quantity, :storage_location, :purchase_shop, :purchase_day, :explanation).merge(user_id: current_user.id)
  end

  def set_commodity
    @commodity = Commodity.find(params[:id])
  end

  def move_to_registration
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :move_to_registration

  def index
    @foods = Food.all.order(id: "DESC")
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to "/foods"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @food.update(food_params)
      redirect_to food_path(@food.id)
    else
      render :edit
    end
  end

  def destroy
    @food.destroy
    redirect_to "/foods"
  end

  private

  def food_params
    params.require(:food).permit(:image, :name, :price, :quantity, :storage_location, :purchase_shop, :purchase_day, :expiration_date, :explanation).merge(user_id: current_user.id)
  end

  def set_food
    @food = Food.find(params[:id])
  end

  def move_to_registration
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :purchase]
  before_action :move_to_registration, except: [:index]

  def index
    @memos = Memo.all.order(id: "DESC")
    @lists = List.all.order(id: "DESC")
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to home_path(@list.id)
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  def purchase
    if @list.update(purchase: true)
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :explanation, :price, :image).merge(user_id: current_user.id, purchase: false)
  end

  def set_list
    @list = List.find(params[:id])
  end

  def move_to_registration
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def create
    memo = Memo.create(memo_params)
    render json:{ memo: memo }
  end

  def checked
    memo = Memo.find(params[:id])
    if memo.checked 
      memo.update(checked: false)
    else
      memo.update(checked: true)
    end

    item = Memo.find(params[:id])
    render json: { memo: item }
  end

  private

  def memo_params
    params.permit(:title, :content).merge(user_id: current_user.id, checked: false)
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @commodities = Commodity.all.order(id: "DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:group_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commodities_helper.rb
module CommoditiesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commodities/edit.html.erb
<div class="items-add-contents">
  <div class="items-add-main">
    <h2 class="items-add-title">在庫の情報を編集</h2>
    <%= form_with model: @commodity, url: commodity_path, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# アイコン %>
      <div class="img-upload">
        <div class="weight-bold-text">
          アイコン
          <span class="optional">任意</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /アイコン %>

      <div class="new-items">
        <div class="weight-bold-text">
          名前
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", placeholder:"名前（必須 40文字まで)", maxlength:"40" %>

        <%# 商品の詳細 %>
        <div class="items-detail">
          <div class="weight-bold-text">商品の詳細</div>
          <div class="items-form">
            <div class="weight-bold-text">
              価格
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :price, class:"items-box", placeholder:"価格（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              個数
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :quantity, class:"items-box", placeholder:"個数（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              保管場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :storage_location, class:"items-box", placeholder:"保管場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :purchase_shop, class:"items-box", placeholder:"購入場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入日
              <span class="optional">任意</span>
            </div>
            <%= f.date_field :purchase_day, class:"items-box", placeholder:"購入日（任意)" %>
          </div>
        </div>
        <%# /商品の詳細 %>

        <div class="items-explain">
          <div class="weight-bold-text">
            メモ
            <span class="optional">任意</span>
          </div>
          <%= f.text_area :explanation, class:"items-text", placeholder:"メモ（任意 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <%# 下部ボタン %>
      <div class="add-btn-contents">
        <%= f.submit "変更する" ,class:"add-btn" %>
        <%=link_to '日用品リストにもどる', "/commodities", class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/commodities/index.html.erb
<div class="wrapper">
  <div class="stocks">
    <div class="stock-list-header">
      <div class="header-name">
        <h1>日用品リスト</h1>
      </div>
      <div class="create-list">
        <a href="/commodities/new">リストに追加する</a>
      </div>
    </div>

    <div class="stock-list">
      <div class='stock-item-contents'>
        <ul class='stock-item-lists'>
          <% if Commodity.exists? && user_signed_in? %>
            <% @commodities.each do |commodity| %>
              <% if commodity.user_id == current_user.id %>
                <li class='stock-item-list'>
                  <%= link_to commodity_path(commodity.id) do %>
                    <div class='stock-item-info'>
                      <div class='stock-name-header'>
                        <P>商品名</p>
                      </div>
                      <div class='stock-img-content-header'>
                        <P>アイコン</p>
                      </div>
                      <div class='stock-quantity-header'>
                        <P>個数</p>
                      </div>
                      <div class='stock-detail-header'>
                        <P>保管場所</p>
                      </div>
                    </div>

                    <hr class ="separate">

                    <div class='stock-item-info'>
                      <div class='stock-name'>
                        <P><%= commodity.name %></p>
                      </div>
                      <div class='stock-img-content'>
                        <% if commodity.image.attached? %>
                          <%= image_tag commodity.image, class: "stock-img" %>
                        <% else %>
                          <%= image_tag "no_image.jpg", class: "stock-img" %>
                        <% end %>
                      </div>
                      <div class='stock-quantity'>
                        <P><%= commodity.quantity %></p>
                      </div>
                      <div class='stock-detail'>
                        <P><%= commodity.storage_location %></p>
                      </div>
                    </div>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          <% end %>

          <%# 商品がない場合のダミー %>
          <% if Commodity.exists? == false && user_signed_in? %>
            <li class='stock-item-list'>
              <%= link_to '/' do %>
                <div class='stock-item-info'>
                  <div class='stock-name-header'>
                    <P>商品名</p>
                  </div>
                  <div class='stock-img-content-header'>
                    <P>アイコン</p>
                  </div>
                  <div class='stock-quantity-header'>
                    <P>個数</p>
                  </div>
                  <div class='stock-detail-header'>
                    <P>保管場所</p>
                  </div>
                </div>

                <hr class ="separate">

                <div class='stock-item-info'>
                  <div class='stock-name'>
                    <P>例）トイレットペーパー</p>
                  </div>
                  <div class='stock-img-content'>
                      <%= image_tag "toilet_roll.jpg", class: "stock-img" %>
                  </div>
                  <div class='stock-quantity'>
                    <P>2</p>
                  </div>
                  <div class='stock-detail'>
                    <P>押入れ</p>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
          <%# /商品がない場合のダミー %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/commodities/new.html.erb
<div class="items-add-contents">
  <div class="items-add-main">
    <h2 class="items-add-title">在庫の情報を入力</h2>
    <%= form_with model: @commodity, url: "/commodities", local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# アイコン %>
      <div class="img-upload">
        <div class="weight-bold-text">
          アイコン
          <span class="optional">任意</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /アイコン %>

      <div class="new-items">
        <div class="weight-bold-text">
          名前
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", placeholder:"名前（必須 40文字まで)", maxlength:"40" %>

        <%# 商品の詳細 %>
        <div class="items-detail">
          <div class="weight-bold-text">商品の詳細</div>
          <div class="items-form">
            <div class="weight-bold-text">
              価格
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :price, class:"items-box", placeholder:"価格（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              個数
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :quantity, class:"items-box", placeholder:"個数（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              保管場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :storage_location, class:"items-box", placeholder:"保管場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :purchase_shop, class:"items-box", placeholder:"購入場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入日
              <span class="optional">任意</span>
            </div>
            <%= f.date_field :purchase_day, class:"items-box", placeholder:"購入日（任意)" %>
          </div>
        </div>
        <%# /商品の詳細 %>

        <div class="items-explain">
          <div class="weight-bold-text">
            メモ
            <span class="optional">任意</span>
          </div>
          <%= f.text_area :explanation, class:"items-text", placeholder:"メモ（任意 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <%# 下部ボタン %>
      <div class="add-btn-contents">
        <%= f.submit "リストに追加する" ,class:"add-btn" %>
        <%=link_to '日用品リストにもどる', "/commodities", class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/commodities/show.html.erb
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @commodity.name %>
    </h2>
    <div class='item-img-content'>
      <% if @commodity.image.attached? %>
        <%= image_tag @commodity.image ,class:"item-box-img" %>
      <% else %>
        <%= image_tag "no_image.jpg", class: "item-box-img" %>
      <% end %>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">価格</th>
          <td class="detail-value"><% unless @commodity.price.nil? %> ¥ <%= @commodity.price.to_s(:delimited) %> <% end %></td>
        </tr>
        <tr>
          <th class="detail-item">個数</th>
          <td class="detail-value"><%= @commodity.quantity %></td>
        </tr>
        <tr>
          <th class="detail-item">保管場所</th>
          <td class="detail-value"><%= @commodity.storage_location %></td>
        </tr>
        <tr>
          <th class="detail-item">購入場所</th>
          <td class="detail-value"><%= @commodity.purchase_shop %></td>
        </tr>
        <tr>
          <th class="detail-item">購入日</th>
          <td class="detail-value"><% unless @commodity.purchase_day.nil? %> <%= @commodity.purchase_day.strftime('%Y年%m月%d日') %> <% end %></td>
        </tr>
        <tr>
          <th class="detail-item">メモ</th>
          <td class="detail-value"><%= @commodity.explanation %></td>
        </tr>
      </tbody>
    </table>

    <%= link_to '内容の編集', edit_commodity_path(@commodity.id), method: :get, class: "item-blue-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', commodity_path(@commodity.id), method: :delete, class:'item-destroy' %>

    <a href="/commodities" class='another-item'>日用品リストにもどる</a>
  </div>
</div>

app/views/foods/edit.html.erb
<div class="items-add-contents">
  <div class="items-add-main">
    <h2 class="items-add-title">在庫の情報を編集</h2>
    <%= form_with model: @food, url: food_path, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# アイコン %>
      <div class="img-upload">
        <div class="weight-bold-text">
          アイコン
          <span class="optional">任意</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /アイコン %>

      <div class="new-items">
        <div class="weight-bold-text">
          名前
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", placeholder:"名前（必須 40文字まで)", maxlength:"40" %>

        <%# 商品の詳細 %>
        <div class="items-detail">
          <div class="weight-bold-text">商品の詳細</div>
          <div class="items-form">
            <div class="weight-bold-text">
              価格
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :price, class:"items-box", placeholder:"価格（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              個数
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :quantity, class:"items-box", placeholder:"個数（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              期限
              <span class="optional">任意</span>
            </div>
            <%= f.date_field :expiration_date, class:"items-box", placeholder:"賞味期限・消費期限（任意)" %>
            <div class="weight-bold-text">
              保管場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :storage_location, class:"items-box", placeholder:"保管場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :purchase_shop, class:"items-box", placeholder:"購入場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入日
              <span class="optional">任意</span>
            </div>
            <%= f.date_field :purchase_day, class:"items-box", placeholder:"購入日（任意)" %>
          </div>
        </div>
        <%# /商品の詳細 %>

        <div class="items-explain">
          <div class="weight-bold-text">
            メモ
            <span class="optional">任意</span>
          </div>
          <%= f.text_area :explanation, class:"items-text", placeholder:"メモ（任意 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <%# 下部ボタン %>
      <div class="add-btn-contents">
        <%= f.submit "変更する" ,class:"add-btn" %>
        <%=link_to '食品リストにもどる', "/foods", class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="items-add-contents">
  <div class="items-add-main">
    <h2 class="items-add-title">在庫の情報を入力</h2>
    <%= form_with model: @food, url: "/foods", local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# アイコン %>
      <div class="img-upload">
        <div class="weight-bold-text">
          アイコン
          <span class="optional">任意</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /アイコン %>

      <div class="new-items">
        <div class="weight-bold-text">
          名前
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", placeholder:"名前（必須 40文字まで)", maxlength:"40" %>

        <%# 商品の詳細 %>
        <div class="items-detail">
          <div class="weight-bold-text">商品の詳細</div>
          <div class="items-form">
            <div class="weight-bold-text">
              価格
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :price, class:"items-box", placeholder:"価格（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              個数
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :quantity, class:"items-box", placeholder:"個数（任意 半角数字で10文字まで)", maxlength:"10" %>
            <div class="weight-bold-text">
              期限
              <span class="optional">任意</span>
            </div>
            <%= f.date_field :expiration_date, class:"items-box", placeholder:"賞味期限・消費期限（任意)" %>
            <div class="weight-bold-text">
              保管場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :storage_location, class:"items-box", placeholder:"保管場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入場所
              <span class="optional">任意</span>
            </div>
            <%= f.text_area :purchase_shop, class:"items-box", placeholder:"購入場所（任意 40文字まで)", maxlength:"40" %>
            <div class="weight-bold-text">
              購入日
              <span class="optional">任意</span>
            </div>
            <%= f.date_field :purchase_day, class:"items-box", placeholder:"購入日（任意)" %>
          </div>
        </div>
        <%# /商品の詳細 %>

        <div class="items-explain">
          <div class="weight-bold-text">
            メモ
            <span class="optional">任意</span>
          </div>
          <%= f.text_area :explanation, class:"items-text", placeholder:"メモ（任意 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>

      <%# 下部ボタン %>
      <div class="add-btn-contents">
        <%= f.submit "リストに追加する" ,class:"add-btn" %>
        <%=link_to '食品リストにもどる', "/foods", class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/foods/show.html.erb
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @food.name %>
    </h2>
    <div class='item-img-content'>
      <% if @food.image.attached? %>
        <%= image_tag @food.image ,class:"item-box-img" %>
      <% else %>
        <%= image_tag "no_image.jpg", class: "item-box-img" %>
      <% end %>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">価格</th>
          <td class="detail-value"><% unless @food.price.nil? %> ¥ <%= @food.price.to_s(:delimited) %> <% end %></td>
        </tr>
        <tr>
          <th class="detail-item">個数</th>
          <td class="detail-value"><%= @food.quantity %></td>
        </tr>
        <tr>
          <th class="detail-item">期限</th>
          <td class="detail-value"><% unless @food.expiration_date.nil? %> <%= @food.expiration_date.strftime('%Y年%m月%d日') %> <% end %></td>
        </tr>
        <tr>
          <th class="detail-item">保管場所</th>
          <td class="detail-value"><%= @food.storage_location %></td>
        </tr>
        <tr>
          <th class="detail-item">購入場所</th>
          <td class="detail-value"><%= @food.purchase_shop %></td>
        </tr>
        <tr>
          <th class="detail-item">購入日</th>
          <td class="detail-value"><% unless @food.purchase_day.nil? %> <%= @food.purchase_day.strftime('%Y年%m月%d日') %> <% end %></td>
        </tr>
        <tr>
          <th class="detail-item">メモ</th>
          <td class="detail-value"><%= @food.explanation %></td>
        </tr>
      </tbody>
    </table>

    <%= link_to '内容の編集', edit_food_path(@food.id), method: :get, class: "item-blue-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', food_path(@food.id), method: :delete, class:'item-destroy' %>

    <a href="/foods" class='another-item'>食品リストにもどる</a>
  </div>
</div>

app/views/homes/_bulletin_board.html.erb
<div class="bulletin-board-header">
  <div class="board-name">
    <h1>『 掲示板 』</h1>
  </div>
  <div class="board-form">
    <%= form_with url: homes_path, method: :post, id: "form" do |form| %>
      <%= form.text_field :title, placeholder: "宛先", class: "memo-text", id: "title" %>
      <%= form.text_area :content, rows: 3, placeholder: "内容", class: "memo-text", id: "content" %>
      <%= form.submit '投稿', id: "submit" %>
    <% end %>
  </div>
</div>

<div class="memos">
  <div id="list">
  </div>
  <% if user_signed_in? %>
    <% @memos.each do |memo| %>
      <% if memo.user_id == current_user.id %>
        <div class="memo" data-id=<%= memo.id %> data-check=<%= memo.checked %> >
          <div class="memo-date">
            <%= l memo.created_at %>
          </div>
          <div class="memo-title">
            To：<%= memo.title %>
          </div>
          <div class="memo-content">
            <%= memo.content %>
          </div>
          <span>既読</span>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/homes/index.html.erb
<div class="wrapper">
  <div class="purchase-list">
    <%= render "purchase_list" %>
  </div>

  <div class="bulletin-board">
    <%= render "bulletin_board" %>
  </div>
</div>

app/views/homes/show.html.erb
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @list.name %>
    </h2>
    <div class='item-img-content'>
      <% if @list.image.attached? %>
        <%= image_tag @list.image ,class:"item-box-img" %>
      <% else %>
        <%= image_tag "no_image.jpg", class: "item-box-img" %>
      <% end %>

      <% if (@list.purchase == true) %>
        <div class='completed'>
          <span>購入完了</span>
        </div>
      <% end %>

    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">連絡事項</th>
          <td class="detail-value"><%= @list.explanation %></td>
        </tr>
        <tr>
          <th class="detail-item">金額の目安</th>
          <td class="detail-value"><%= @list.price %></td>
        </tr>
      </tbody>
    </table>

    <%= button_to "購入完了", {controller: 'homes', action: 'purchase'}, {method: :patch, class: "item-red-btn", params: {id: @list.id}} %>

    <hr>

    <%= link_to '内容の編集', edit_home_path(@list.id), method: :get, class: "item-blue-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', home_path(@list.id), method: :delete, class:'item-destroy' %>

    <a href="/" class='another-item'>トップページにもどる</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Family ~memo~</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="tittle-bar">
        <div class="tittle">
          <a href = "/">
            Family ~memo~<br>
            <span class = "sub-tittle">-お家の掲示板-</span>
          </a>
        </div>
      </div>

      <nav class="navigation-bar">
        <div class="menu">
          <h1>在庫：</h1>
          <div class="menu-name enclosure">
            <ul>
              <li><a href="/commodities">日用品</a></li>
              <li><a href="/foods">食品</a></li>
              <li><a href="#">その他</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <nav class="user-nav">
        <ul class="user-nav-list">
          <% if user_signed_in? %>
            <li><%= link_to current_user.group_name, edit_user_path(current_user), class: "user-groupname " %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-btn " %></li> 
          <% else %>
            <li><%= link_to 'アカウント登録', new_user_registration_path, class: "nav-btn " %></li>
            <li><%= link_to 'ログイン', new_user_session_path, class: "nav-btn " %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <%# 後ほど修正を加える %>
      <p>&copy; 2021 Jun_Nishimura</p>
    </footer>
  </body>
</html>